### PR TITLE
yaml is missing on the requirement

### PR DESCRIPTION
**Pull request by azlux**

### CODE REVIEW

**Comment by azlux** [comment]
Appear while testing the installation on Windows

**Comment by el-dee** [comment]
Sorry, this PR slipped under my radar :)

Could you tell me what when wrong with the installation ? PyYAML is shipped in the source (https://github.com/cosmonium/cosmonium/tree/master/cosmonium/support/yaml) so it should not be explicitly specified in requirements.txt

PyYAML is included in the source as there are not wheels for all the platforms and Panda3D Deploy-NG does not support source tgz.

**Comment by azlux** [comment]
$ ./main.py
```
Traceback (most recent call last):
  File "C:\Users\dmichel\Documents\Git\cosmonium\cosmonium\parsers\yamlparser.py", line 19, in <module>
    from yaml import CLoader as Loader
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 5, in <module>
    from cosmonium.cosmonium import Cosmonium
  File "C:\Users\dmichel\Documents\Git\cosmonium\cosmonium\__init__.py", line 5, in <module>
    from .parsers.configparser import configParser
  File "C:\Users\dmichel\Documents\Git\cosmonium\cosmonium\parsers\__init__.py", line 4, in <module>
    from . import objectparser
  File "C:\Users\dmichel\Documents\Git\cosmonium\cosmonium\parsers\objectparser.py", line 8, in <module>
    from .yamlparser import YamlModuleParser
  File "C:\Users\dmichel\Documents\Git\cosmonium\cosmonium\parsers\yamlparser.py", line 21, in <module>
    from yaml import Loader
ModuleNotFoundError: No module named 'yaml'
```
-> https://github.com/cosmonium/cosmonium/blob/master/cosmonium/parsers/yamlparser.py#L21

**Comment by el-dee** [comment]
Ah, I see! As almost all my host are used for dev, they have PyYAML installed too and so the re-import is successful :(

Thank you for the investigation!

**Comment by el-dee** [comment]
Fixed in https://github.com/cosmonium/cosmonium/tree/dev_v0.1.1

**Pull request closed without merging**
